version: '3'

services:
  web:
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "./:/app"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=riderexpert
      - DJANGO_DB_USER=riderexpert
      - DJANGO_DB_PASSWORD=testdatabase

  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=riderexpert
      - POSTGRES_USER=riderexpert
      - POSTGRES_PASSWORD=testdatabase

  redis:
    image: redis:latest

  celery:
    build: .
    command: celery -A riderexpert worker --loglevel=info
    volumes:
      - "./:/app"
    depends_on:
      - db
      - web
      - redis
    environment:
      - DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=riderexpert
      - DJANGO_DB_USER=riderexpert
      - DJANGO_DB_PASSWORD=testdatabase


  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
    - "1080:1080"
    - "1026:1025"

volumes:
  postgres_data:
