version: '3'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "./:/app"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=riderexpert
      - DJANGO_DB_USER=riderexpert
      - DJANGO_DB_PASSWORD=testdatabase

  db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=riderexpert
      - POSTGRES_USER=riderexpert
      - POSTGRES_PASSWORD=testdatabase

volumes:
  postgres_data: