databases:
  - name: riderexpert
    plan: free
    databaseName: riderexpert
    user: riderexpert

services:
  - type: web
    name: web
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn riderexpert.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysitedb
          property: connectionString
      - key: ENVIRON
        value: test
      - key: WEB_CONCURRENCY
        value: 4
