# Generated by Django 4.1.6 on 2023-12-07 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(default='TWO_WHEELER', max_length=50)),
                ('vehicle_registration_number', models.CharField(max_length=20, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('min_capacity', models.PositiveIntegerField()),
                ('max_capacity', models.PositiveIntegerField()),
                ('fragile_item_allowed', models.BooleanField(default=True)),
                ('charge_per_mile', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ratings', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
