# Generated by Django 4.1.6 on 2023-12-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_email_otp_userverification_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='charge_per_mile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='fragile_item_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='min_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='ratings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='vehicle_type',
            field=models.CharField(default='TWO_WHEELER', max_length=50),
        ),
    ]
