# Generated by Django 4.1.6 on 2023-11-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_customer_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_email_verified',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
