# Generated by Django 4.1.6 on 2024-02-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_rider_is_available_rider_charge_per_mile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rider',
            name='vehicle_type',
            field=models.CharField(default='TWO_WHEELER', max_length=50),
        ),
    ]
