# Generated by Django 4.1.6 on 2024-02-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userverification_used_alter_rider_vehicle_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='charge_per_mile',
            new_name='charge_per_km',
        ),
    ]
