# Generated by Django 4.1.6 on 2024-02-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_charge_per_mile_rider_charge_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='declined_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rider',
            name='completed_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rider',
            name='declined_requests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
