# Generated by Django 4.1.6 on 2024-03-04 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_declined_requests_rider_completed_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_account_verification', models.BooleanField(default=False)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.rider')),
            ],
        ),
    ]
