# Generated by Django 4.1.6 on 2024-12-30 18:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_riderverification'),
        ('multi_orders', '0002_feedback_customer_orderriderassignment_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderriderassignment',
            name='assigned_weight',
        ),
        migrations.RemoveField(
            model_name='orderriderassignment',
            name='destination',
        ),
        migrations.AddField(
            model_name='orderriderassignment',
            name='package_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderriderassignment',
            name='package_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='orderriderassignment',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderriderassignment',
            name='pickup_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderriderassignment',
            name='pickup_long',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderriderassignment',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderriderassignment',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderriderassignment',
            name='recipient_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orderriderassignment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderriderassignment',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.rider'),
        ),
    ]
