# Generated by Django 4.1.6 on 2024-03-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_pendingwallettransaction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
