# Generated by Django 4.1.6 on 2023-12-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_email_otp_userverification_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.TextField()),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PendingPickup', 'Pending Pickup'), ('WaitingForPickup', 'Waiting for pickup'), ('PickedUp', 'Picked up'), ('InTransit', 'In transit'), ('Arrived', 'Arrived'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], max_length=20)),
                ('recipients_name', models.CharField(max_length=100)),
                ('recipient_address', models.TextField()),
                ('recipient_phone_number', models.CharField(max_length=15)),
                ('order_completion_code', models.CharField(max_length=10)),
                ('parcel_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parcel_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fragile', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('rider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.rider')),
            ],
        ),
    ]
