# Generated by Django 4.1.6 on 2024-02-27 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customer_declined_requests_rider_completed_orders_and_more'),
        ('orders', '0003_order_creation_time_order_name_order_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='recipients_name',
            new_name='recipient_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='parcel_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='parcel_weight',
            new_name='weight',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeclinedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decline_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.rider')),
            ],
        ),
    ]
