# Generated by Django 4.1.6 on 2024-03-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PendingPickup', 'Pending Pickup'), ('WaitingForPickup', 'Waiting for pickup'), ('PickedUp', 'Picked up'), ('InTransit', 'In transit'), ('Arrived', 'Arrived'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Created', 'Created'), ('RiderSearch', 'RiderSearch')], default='Created', max_length=20),
        ),
    ]
