# Generated by Django 4.1.6 on 2024-12-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='destinations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_bulk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PendingPickup', 'Pending Pickup'), ('WaitingForPickup', 'Waiting for pickup'), ('PickedUp', 'Picked up'), ('InTransit', 'In transit'), ('Arrived', 'Arrived'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Created', 'Created'), ('RiderSearch', 'RiderSearch'), ('Assigned', 'Assigned'), ('PartiallyAssigned', 'Partially Assigned')], default='Created', max_length=20),
        ),
    ]
