# Generated by Django 4.1.6 on 2025-01-02 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_value_alter_order_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
